services:
  vit-cnn-research:
    build: .
    container_name: vit_cnn_medical
    shm_size: '2gb'
    volumes:
      - ./data:/app/data
      - ./results:/app/results
      - ./logs:/app/logs
      - ./checkpoints:/app/checkpoints
      - ./src:/app/src
      - ./scripts:/app/scripts
      - ./config.py:/app/config.py
      - ./main.py:/app/main.py
      - ./test_setup.py:/app/test_setup.py
    environment:
      - PYTHONPATH=/app
      - WANDB_API_KEY=${WANDB_API_KEY}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    command: python test_setup.py
    
  prepare-data:
    build: .
    container_name: vit_cnn_prepare_data
    shm_size: '2gb'
    volumes:
      - ./data:/app/data
      - ./src:/app/src
      - ./scripts:/app/scripts
      - ./.env:/app/.env
    environment:
      - PYTHONPATH=/app
      - KAGGLE_USERNAME=${KAGGLE_USERNAME}
      - KAGGLE_KEY=${KAGGLE_KEY}
    command: python scripts/prepare_dataset.py

  test:
    build: .
    container_name: vit_cnn_test
    shm_size: '2gb'
    volumes:
      - ./data:/app/data
      - ./results:/app/results
      - ./src:/app/src
      - ./config.py:/app/config.py
      - ./main.py:/app/main.py
      - ./test_setup.py:/app/test_setup.py
    environment:
      - PYTHONPATH=/app
      - WANDB_API_KEY=${WANDB_API_KEY}
    command: python test_setup.py
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    
  experiment:
    build: .
    shm_size: '2gb'
    volumes:
      - ./data:/app/data
      - ./results:/app/results
      - ./logs:/app/logs
      - ./checkpoints:/app/checkpoints
      - ./src:/app/src
      - ./scripts:/app/scripts
      - ./config.py:/app/config.py
      - ./main.py:/app/main.py
    environment:
      - PYTHONPATH=/app
      - WANDB_API_KEY=${WANDB_API_KEY}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    command: python main.py --mode single --model_type cnn --model_name resnet18 --fraction 0.1
    
  comparison:
    build: .
    container_name: vit_cnn_comparison
    shm_size: '2gb'
    volumes:
      - ./data:/app/data
      - ./results:/app/results
      - ./logs:/app/logs
      - ./checkpoints:/app/checkpoints
      - ./src:/app/src
      - ./scripts:/app/scripts
      - ./config.py:/app/config.py
      - ./main.py:/app/main.py
    environment:
      - PYTHONPATH=/app
      - WANDB_API_KEY=${WANDB_API_KEY}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    command: python main.py --mode comparison

networks:
  default:
    name: vit_cnn_network 